//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soulsplit.Api.Email.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soulsplit.Api.Email.Properties.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;
        ///      xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        ///      style=&quot;
        ///    width: 100%;
        ///    font-family: arial, &apos;helvetica neue&apos;, helvetica, sans-serif;
        ///    -webkit-text-size-adjust: 100%;
        ///    -ms-text-size-adjust: 100%;
        ///    padding: 0;
        ///    margin: 0;
        ///  &quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;meta content=&quot;width=device-width, ini [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivarUsuario {
            get {
                return ResourceManager.GetString("ActivarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html
        ///  xmlns=&quot;http://www.w3.org/1999/xhtml&quot;
        ///  xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        ///  style=&quot;
        ///    width: 100%;
        ///    font-family: arial, &apos;helvetica neue&apos;, helvetica, sans-serif;
        ///    -webkit-text-size-adjust: 100%;
        ///    -ms-text-size-adjust: 100%;
        ///    padding: 0;
        ///    margin: 0;
        ///  &quot;
        ///&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;meta content=&quot;width=device-width, init [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cambioclave {
            get {
                return ResourceManager.GetString("Cambioclave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html
        ///  xmlns=&quot;http://www.w3.org/1999/xhtml&quot;
        ///  xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        ///  style=&quot;
        ///    width: 100%;
        ///    font-family: arial, &apos;helvetica neue&apos;, helvetica, sans-serif;
        ///    -webkit-text-size-adjust: 100%;
        ///    -ms-text-size-adjust: 100%;
        ///    padding: 0;
        ///    margin: 0;
        ///  &quot;
        ///&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;meta content=&quot;width=device-width, init [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contacto {
            get {
                return ResourceManager.GetString("contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html
        ///  xmlns=&quot;http://www.w3.org/1999/xhtml&quot;
        ///  xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        ///  style=&quot;
        ///    width: 100%;
        ///    font-family: arial, &apos;helvetica neue&apos;, helvetica, sans-serif;
        ///    -webkit-text-size-adjust: 100%;
        ///    -ms-text-size-adjust: 100%;
        ///    padding: 0;
        ///    margin: 0;
        ///  &quot;
        ///&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;meta content=&quot;width=device-width, init [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnvioCuentas {
            get {
                return ResourceManager.GetString("EnvioCuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot;
        ///      xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;/&gt;
        ///    &lt;meta name=&quot;x-apple-disable [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UsuarioClaveNueva {
            get {
                return ResourceManager.GetString("UsuarioClaveNueva", resourceCulture);
            }
        }
    }
}
