CREATE USER nacho WITH PASSWORD 'nachoClave@H' VALID UNTIL '3050-01-01';
CREATE USER ronald WITH PASSWORD 'chichaClave@R' VALID UNTIL '3050-01-01';
CREATE USER sebas WITH PASSWORD 'mate@32115' VALID UNTIL '3050-01-01';
CREATE USER netcore WITH PASSWORD 'PZ$KTwiO9' VALID UNTIL '3050-01-01';


ALTER USER nacho WITH SUPERUSER;
ALTER USER sebas WITH SUPERUSER;
ALTER USER ronald WITH SUPERUSER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO netcore;
GRANT ALL PRIVILEGES ON DATABASE trading TO netcore;
